project:
  type: book
  output-dir: docs
book:
  # başlık: "LaTeX Dersleri"  # Quarto'da 'title' anahtarını kullanmak zorundasınız, ancak başlık için Türkçe açıklama eklenebilir
  title: "LaTeX Dersleri"
  # yazar: "Ali İhsan ÇANAKOĞLU"  # Quarto'da 'author' anahtarını kullanmak zorundasınız, ancak yazar için Türkçe açıklama eklenebilir
  author: "Ali İhsan ÇANAKOĞLU"
  # bölümler:  # Quarto'da 'chapters' anahtarını kullanmak zorundasınız, ancak bölümler için Türkçe açıklama eklenebilir
  chapters:
    - index.qmd
    - chapters/introduction.qmd
    - chapters/chapter1.qmd
    - chapters/resim-ekleme.qmd
    - chapters/listeleme.qmd
    - chapters/matematik.qmd
    - chapters/tablolama.qmd
    - chapters/tikz.qmd
    - chapters/pgf.qmd
    - chapters/komut-tanimlama.qmd
format:
  html:
    theme: superhero
    code-fold: true
    css: styles.css
